don't bother without having 'unzip', luarocks requires it

diff --git a/crater b/crater
--- a/crater
+++ b/crater
@@ -57,6 +57,13 @@ package_url() {
   return $?
 }
 
+check_prereqs() {
+  if ! command -v 'unzip'; then
+    echo "'unzip' not installed, required by luarocks." 1>&2
+    return 1
+  fi
+}
+
 download() {
   local _curl; _curl="$(command -v curl)";
   if [ "x$_curl" != "x" ]; then
@@ -187,7 +194,8 @@ install_lua() {
         (cd "$_install_prefix/bin" && ln -s luajit lua)
       fi
 
-  ) > "$crater_install_dir/.log_install_lua" 2>&1
+  ) 2>&1 | tee "$crater_install_dir/.log_install_lua"
+  return ${PIPESTATUS[0]};
 }
 
 install_luarocks() {
@@ -203,7 +211,8 @@ install_luarocks() {
       make &&
       make install &&
       cd ../ && rm -rvf "$_luarocks_src"
-  ) > "$crater_install_dir/.log_install_luarocks" 2>&1
+  ) 2>&1 | tee "$crater_install_dir/.log_install_luarocks"
+  return ${PIPESTATUS[0]};
 }
 
 CRATER_ROOT=${CRATER_ROOT:="$PWD/.crater"}
@@ -244,8 +253,9 @@ mkdir -p "$crater_tmp_dir" "$crater_cache_dir" "$crater_install_dir"
   set -x; export SHELLOPTS;
 
   if ! check_installed "$lua_tgz_sha1" "$luarocks_tgz_sha1" ; then
-    rm -rf "$crater_install_dir/"{*,.[!.]*,..?*}
-    install_lua "$lua_tgz_url" "$lua_tgz_sha1" &&
+    rm -rf "$crater_install_dir"
+    check_prereqs &&
+      install_lua "$lua_tgz_url" "$lua_tgz_sha1" &&
       install_luarocks "$luarocks_tgz_url" "$luarocks_tgz_sha1" &&
       mark_installed "$lua_tgz_sha1" "$luarocks_tgz_sha1" &&
       rm -rf "$crater_tmp_dir"/{*,.[!.]*,..?*}
